site_name: Black个人专栏
theme:
  name: "material"
  #  font: false
  feature:
    tabs: true
  palette:
    primary: blue
    accent: red
  language: "zh"
repo_url: https://github.com/chanclass/myclass

copyright: "Copyright &copy; 2015 - 2019 Vincent Chan"

plugins:
  - search

#google_analytics:
#  - "UA-78705624-3"
#  - "auto"

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  # pymdown-extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight:
      # css_class: codehilite # https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml
      extend_pygments_lang:
        - name: python
          lang: python
          options:
            startinline: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - static/css/extra.css

extra_javascript:
  - static/js/baidu-static.js
  - static/js/math.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  social:
    - type: github-alt
      link: https://github.com/JayChen123

nav:
  - 首页:
      - index.md
  - 深度学习:
      - DeepLearning/keras的Tokenizer源码解读.md
      - DeepLearning/WordEmbedding深入解读.md
  # - Latex:
  #     - latex/介绍.md
  #     - latex/latex入门.md
  #     - latex/latex安装.md
  # - OpenFOAM:
  #     - openfoam/介绍.md
  #     - openfoam/基础命令.md
  #     - openfoam/安装.md
  - Python:
      - python/列表展开式.md
      - python/pdf/操作PDF.md
      - python/pdf/操作PDF页面.md
  - 中学生编程:
      - 介绍: midStudent/介绍.md
      - 第一章 环境搭建:
          - 什么是操作系统: midStudent/第1章/1.1 什么是操作系统.md
          - 如何搭建环境: midStudent/第1章/1.2 如何搭建Python.md
          - 为什么学Python: midStudent/第1章/1.3 为什么学Python.md
      - 第二章 基础:
          - 开始编程: midStudent/第2章/2.1 开始编程.md
          - 基础数据: midStudent/第2章/2.2 基础数据.md
          - 变量是什么: midStudent/第2章/2.3 变量.md
          - 创建程序:  midStudent/第2章/2.4 创建程序.md
      - 第三章 逻辑:
          - 判断正数: midStudent/第3章/3.1 判断是否正数.md
          - 计算方程: midStudent/第3章/3.2 计算方程.md
          - 从1加到100: midStudent/第3章/3.3 从1加到100.md
          - 数学函数的介绍: midStudent/第3章/3.4 数学函数的介绍.md
          - 复数的计算: midStudent/第3章/3.5 复数的计算.md
          - 猜数字游戏: midStudent/第3章/3.6 猜数字游戏.md
      - 第四章 函数:
          - 函数的初步: midStudent/第4章/4.1 函数的初步.md
          - 计算闰年: midStudent/第4章/4.2 计算闰年.md
          - 计算圆周率: midStudent/第4章/4.3 计算圆周率.md
          - 手动实现四则运算: midStudent/第4章/4.4 手动实现四则运算.md
          - 生成四则运算题: midStudent/第4章/4.5 生成四则运算题.md
          - 斐波拉契数列: midStudent/第4章/4.6 斐波拉契数列.md
          - 小试数列: midStudent/第4章/4.7 小试数列.md
      - 第五章 包管理:
          - 包的导入与使用: midStudent/第5章/5.1 包的导入.md
          - 自定义包: midStudent/第5章/5.2 自定义包.md
          - 如何寻求帮助: midStudent/第5章/5.3 如何寻求帮助.md
          - 安装第三方模块: midStudent/第5章/5.4 安装第三方模块.md
      - 第六章 可视化:
          - 函数图像: midStudent/第6章/6.1 画函数图像.md

  - 关于:
      - 关于作者.md
